### ISSUE TITLE
option to change meaurement units

### ISSUE THREAD

**Issue by simon1tan** [aprilandjan/leaflet.measure#1]
Thank you for the plugin. It would be nice to be able to switch to miles for the dumb countries who can't switch to the metric system..

**Comment by aprilandjan** [comment]
Hi, thanks for your notice. This plugin dose not support customized distance format method yet, but since it's not complicated, I made a little improvement to support it. Use option `formatDistance`, you can customize measure unit as you wish. For example:

```javascript
L.control.measure({
  //  distance formatter, output mile instead of km 
  formatDistance: function (val) {
    return Math.round(1000 * val / 1609.344) / 1000 + 'mile';
  }
}).addTo(map)
```
