### ISSUE TITLE
Active from external button?

### ISSUE THREAD

**Issue by simon1tan** [aprilandjan/leaflet.measure#2]
Is there a way to manually activate? I have my own buttons that are aligned so adding this button by itself doesn't work well. So I created my own button but haven't figured if I can activate measurement manually.

**Comment by aprilandjan** [comment]
@simon1tan You mean you want to hide the default measure button but with the ability to toggle measure status? If so it is possible. The plugin instance is returned when add to map, so you can use this instance to manually call plugin method like this:

```javascript
var measurePlugin = L.control.measure().addTo(map)
//  call plugin internal method manually. _toggleMeasure() toggles measuring state
measurePlugin._toggleMeasure();
```

besides, you might need to set the measure control div `.leaflet-control-measure` as `display: none`.

Hope this helps.
