### ISSUE TITLE
Cursor flickering on moving/dragging

### ISSUE THREAD

**Issue by takvol** [aprilandjan/leaflet.measure#4]
Issue: cursor is flickering on moving/dragging.
Reason: measure polyline has `leaflet-interactive` class. When `leaflet-interactive` element gets hovered, cursor style changes to "pointer"/"grabbing".
<details>
<summary>GIF example</summary>

![leaflet-measure](https://user-images.githubusercontent.com/18425869/52466522-3455d680-2b8b-11e9-88d4-417e6d33e76b.gif)

</details>
Please see #5 for a possible solution

**Comment by aprilandjan** [comment]
@takvol Thanks very much, I didn't notice that detail before. your solution works greatly 👍
