### ISSUE TITLE
CRS Simple

### ISSUE THREAD

**Issue by mikaelhug** [aprilandjan/leaflet.measure#6]
Hello!
Im wondering how I would go about to make this tool work for non geographical maps?

Using it as is with CRS.Simple map obviosuly doesnt work. I tried to change:
var distance = e.latlng.distanceTo(this._lastPoint)  ---->
var distance = e.latlng.distance(this._lastPoint)

However, this doesnt seem to work either. Any advice?
Thank you

**Comment by aprilandjan** [comment]
@mhugen I didn't use CRS map before, need to take some time to check it. For now I'm afraid I have no idea 😢

**Comment by mikaelhug** [comment]
@mhugen In case someone else is wondering the same thing, I was able to figure it out. The lines 140 and 161 has to be changed to:
var distance = this._map.distance(e.latlng, this._lastPoint)

Thats all. Now it will display distance for CRS.Simple. You might have to change the math rounding to display m,cm,mm whatever your map is in. Thank you for the reply and great plugin!

**Comment by aprilandjan** [comment]
@mhugen  that is a nice solution! Thanks for sharing!
