### ISSUE TITLE
Not able to finish a measure over the top of a layer

### ISSUE THREAD

**Issue by ping-spike** [aprilandjan/leaflet.measure#8]
If you have any layers displayed on the map, you can start a measure to the left of the layer (eg. polygon) and end it beyond the polygon, but you can not end the measurement ON the polygon.

**Comment by ping-spike** [comment]
Example of measure **working ok** if you go beyond a layer:

![Screen Shot 2020-08-18 at 20 12 44](https://user-images.githubusercontent.com/37631040/90555499-5ae8ca80-e18f-11ea-887f-c9642ce1f996.png)

**Comment by ping-spike** [comment]
But if you try to click on the layer / polygon area to end the measure, instead of ending the measure the info balloon appears for that map layer / polygon:

![Screen Shot 2020-08-18 at 20 13 36](https://user-images.githubusercontent.com/37631040/90555568-78b62f80-e18f-11ea-88f4-eb789b267964.png)

**Comment by ping-spike** [comment]
Is there a way to disable clicks on visible layers when the measure tool is turned on,  then re-enable clicks on the layers when it is turned off again? 🤔

**Comment by aprilandjan** [comment]
@ping-spike hi, thanks for your feedback!

It seems that once we add popup to the layer/polygon, the click on it will be captured first and stops further event propagation, thus makes the measure layer cannot get the click event to draw line (https://github.com/Leaflet/Leaflet/issues/765).

How ever, we can bypass that though some **tricky** methods. For example, when start measuring, loop through all layers and remove their click event handlers to prevent them from responding to click; and then, after finish measuring, we add back their click event handlers to keep its original behavior.

**Comment by ping-spike** [comment]
Agreed, sounds tricky :grimacing: 

We almost need an `interactive: false` being applied to each active layer :thinking: 

Any pointers that I could experiment with?

**Comment by aprilandjan** [comment]
I wrote some experimental code in branch [feat/disable-other-clicks-while-measuring] (https://github.com/aprilandjan/leaflet.measure/tree/feat/disable-other-clicks-while-measuring), add an option `disableOtherClicksWhileMeasuring` to implement that, please have a try.

Here's the tricky:

```javascript
  //  the cached clicks for other layers
  _cachedClicks: [],

  //  try to remove click event handlers of other layers
  _removeOtherLayersClicks: function (layer) {
    if (layer === this._layerPaint) {
      return;
    }
    var loop = function (childLayer) {
      if (childLayer._events && childLayer._events.click) {
        this._cachedClicks.push({
          layer: childLayer,
          click: childLayer._events.click,
        });
        childLayer._events.click = undefined;
      }
      if (childLayer.eachLayer) {
        this._removeOtherLayersClicks(childLayer);
      }
    }.bind(this);
    layer.eachLayer(loop);
  },

  //  try to bring back the click event handlers
  _addOtherLayersClicks: function () {
    this._cachedClicks.forEach(function (cached) {
      var layer = cached.layer;
      var click = cached.click;
      layer._events.click = click;
    });
  },
```

**Comment by ping-spike** [comment]
Amazing work!

Tested and seems to work perfectly :clap: 

If I'm mid-measure and zoom the map in or out it seems to re-enable the layer clickability again. But hey, that's a minor.

This is fantastic, thanks for the seriously quick response times :)

**Comment by aprilandjan** [comment]
@ping-spike you are welcome 😄
